# Generated by Django 4.2.2 on 2023-08-31 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=50)),
                ('assignment_description', models.TextField()),
                ('assignment_due_date', models.DateField()),
                ('assignment_score', models.IntegerField()),
                ('assignment_created', models.DateTimeField(auto_now_add=True)),
                ('assign_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_from', to=settings.AUTH_USER_MODEL)),
                ('assign_to', models.ManyToManyField(related_name='assign_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
