# Generated by Django 4.2.2 on 2023-09-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assign_is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assign_student_asnwer',
            field=models.TextField(blank=True),
        ),
    ]
