# Generated by Django 4.2.2 on 2023-09-01 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_assign_is_submitted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assign_student_asnwer',
            new_name='assign_student_answer',
        ),
    ]
