# Generated by Django 4.2.2 on 2023-09-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_alter_submittedassignments_assignment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedassignments',
            old_name='assign_is_submitted',
            new_name='assignment_is_submitted',
        ),
    ]
