# Generated by Django 4.2.2 on 2023-09-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_rename_assignment_submitted_date_submittedassignments_assignment_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignments',
            name='assignment_obtain_score',
            field=models.FloatField(default=0),
        ),
    ]
